name: Integration test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dodona-edu/dodona-python:latest
      options: --user root

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install test dependencies
        run: ./devel/install_test_deps.sh
      - name: Run tests
        run: ./devel/run-tests.sh
      - name: Code Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
